# This file was generated by GoReleaser. DO NOT EDIT.
cask "goatway" do
  name "goatway"
  desc "Lightweight, streaming-safe, OpenAI-compatible HTTP proxy for LLM providers"
  homepage "https://github.com/mandalnilabja/goatway"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goatway"

  on_macos do
    on_intel do
      url "https://github.com/mandalnilabja/goatway/releases/download/v#{version}/goatway_#{version}_darwin_amd64.tar.gz"
      sha256 "b5d47de0ba237e4dae35373d7844f8a25e5815dd2ea04acafae67d17a9ed2b34"
    end
    on_arm do
      url "https://github.com/mandalnilabja/goatway/releases/download/v#{version}/goatway_#{version}_darwin_arm64.tar.gz"
      sha256 "e0f80c892aff33dc95eff8582772e2748ec72763ec7bab2f8bd76a9625641327"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mandalnilabja/goatway/releases/download/v#{version}/goatway_#{version}_linux_amd64.tar.gz"
      sha256 "6f59176814f15f0d761ff5818bfa244c5991ef2c696877ab8925d47e7d7632cd"
    end
    on_arm do
      url "https://github.com/mandalnilabja/goatway/releases/download/v#{version}/goatway_#{version}_linux_arm64.tar.gz"
      sha256 "5038ee349dff35e266042a14c7e448dbc1e0f1ba7d24e9b9cb8dafa5bbc9c4ed"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/goatway"]
    end
  end

  caveats do
    "If macOS shows 'goatway is damaged', run:"
    "  xattr -dr com.apple.quarantine $(which goatway)"
  end

  # No zap stanza required
end
