# This file was generated by GoReleaser. DO NOT EDIT.
cask "goatway" do
  name "goatway"
  desc "Lightweight, streaming-safe, OpenAI-compatible HTTP proxy for LLM providers"
  homepage "https://github.com/mandalnilabja/goatway"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goatway"

  on_macos do
    on_intel do
      url "https://github.com/mandalnilabja/goatway/releases/download/v#{version}/goatway_#{version}_darwin_amd64.tar.gz"
      sha256 "e62e6412504c2f7b6f18c67ea7777c1af69795d2068e66690776837012b22211"
    end
    on_arm do
      url "https://github.com/mandalnilabja/goatway/releases/download/v#{version}/goatway_#{version}_darwin_arm64.tar.gz"
      sha256 "1242d02cdc089b7e2bfd1032f37b837f22052bc7cfec36a930760d56b4f98fcf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mandalnilabja/goatway/releases/download/v#{version}/goatway_#{version}_linux_amd64.tar.gz"
      sha256 "0fe1a0ce39590b3e2d748494c28b6a3dc3bd15521558f92829c37a6a562bc36d"
    end
    on_arm do
      url "https://github.com/mandalnilabja/goatway/releases/download/v#{version}/goatway_#{version}_linux_arm64.tar.gz"
      sha256 "943f442ecc573e60982c4eca4f4ce407f6c3f9daf05e5cf2045bdbd0df397269"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/goatway"]
    end
  end

  caveats do
    "If macOS shows 'goatway is damaged', run:"
    "  xattr -dr com.apple.quarantine $(which goatway)"
  end

  # No zap stanza required
end
