# This file was generated by GoReleaser. DO NOT EDIT.
cask "goatway" do
  name "goatway"
  desc "Lightweight, streaming-safe, OpenAI-compatible HTTP proxy for LLM providers"
  homepage "https://github.com/mandalnilabja/goatway"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goatway"

  on_macos do
    on_intel do
      url "https://github.com/mandalnilabja/goatway/releases/download/v#{version}/goatway_#{version}_darwin_amd64.tar.gz"
      sha256 "ca4fe27e317af335836b276ea73e8c82add2d09d6341d2cd22cc1f3f89c97f9e"
    end
    on_arm do
      url "https://github.com/mandalnilabja/goatway/releases/download/v#{version}/goatway_#{version}_darwin_arm64.tar.gz"
      sha256 "8400bd07c60207cb7b5ecfbb5b52c756144c7a3b0e220e75a37bf03f4e6298bf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mandalnilabja/goatway/releases/download/v#{version}/goatway_#{version}_linux_amd64.tar.gz"
      sha256 "ead241fc6be811b719e647a608a06da2f6c643f14284ad1f9bfb44fbf85bba6c"
    end
    on_arm do
      url "https://github.com/mandalnilabja/goatway/releases/download/v#{version}/goatway_#{version}_linux_arm64.tar.gz"
      sha256 "ad7e74c403e1969b6afb309d603ea156a04d9ef05f874436937f5750751cb314"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/goatway"]
    end
  end

  caveats do
    "If macOS shows "goatway is damaged", run:"
    "  xattr -dr com.apple.quarantine $(which goatway)"
  end

  # No zap stanza required
end
